services:
  - type: web
    name: sepsis-watch-demo
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
